name: PHPUnit-Swow

on: [ push, pull_request ]

env:
  DAEMONIZE: '(true)'
jobs:
  ci:
    name: Test PHP ${{ matrix.php }} on Swow ${{ matrix.swow }}
    runs-on: "${{ matrix.os }}"
    env:
      SWOW_VERSION: ${{ matrix.swow }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        php: [ '8.0', '8.1', '8.2' ]
        swow: [ 'v1.2.0', 'develop' ]
      max-parallel: 16
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: phpize
          extensions: redis, pdo, pdo_mysql, bcmath
          ini-values: opcache.enable_cli=0, swoole.use_shortname='Off'
          coverage: none
      - name: Setup Swow
        run: |
          wget https://github.com/swow/swow/archive/"${SWOW_VERSION}".tar.gz -O swow.tar.gz
          mkdir -p swow
          tar -xf swow.tar.gz -C swow --strip-components=1
          rm swow.tar.gz
          cd swow/ext || exit

          phpize
          ./configure --enable-debug
          make -j "$(nproc)"
          sudo make install
          sudo sh -c "echo extension=swow > /etc/php/${{ matrix.php }}/cli/conf.d/swow.ini"
          php --ri swow
      - name: Setup Services
        run: docker run --name mysql -p 3306:3306 -e MYSQL_ALLOW_EMPTY_PASSWORD=true -d mysql:5.7 --bind-address=0.0.0.0 --default-authentication-plugin=mysql_native_password
      - name: Setup MySQL
        run: export TRAVIS_BUILD_DIR=$(pwd) && bash ./.travis/setup.mysql.sh
      - name: Setup Packages
        run: composer update -o --no-scripts
      - name: Run Server
        run: |
          php example/swow.php start
          sleep 5
      - name: Run Analyse
        run: |
          composer analyse src
      - name: Run Test Cases
        run: |
          composer test
